/**
 * Custom Workers entry in front of the OpenNext-generated handler.
 *
 * Two jobs:
 *
 * 1. Serve /webzjs/* from R2. Workers static assets cap single files at
 *    25 MB and webzjs_wallet_bg.wasm is 57 MB, so the wallet artifacts
 *    cannot ship in the asset bundle. Serving them from R2 under the same
 *    /webzjs/ paths keeps the unbundled import() in WebZjsProvider working
 *    identically in dev and production, with no CORS involved.
 *
 * 2. Guarantee the headers next.config.mjs declares. OpenNext forwards them
 *    on its own responses; the set-if-absent pass below is a safety net so
 *    an adapter upgrade cannot silently drop them. Keep PAGE_HEADERS in
 *    sync with the headers() block in next.config.mjs.
 *
 * Excluded from tsconfig: it imports the generated .open-next bundle, which
 * tsc should never crawl. Wrangler bundles this with esbuild at deploy.
 */

// @ts-expect-error -- generated by `opennextjs-cloudflare build`
import handler from './.open-next/worker.js';

interface WebzjsBucket {
  get(key: string): Promise<{ body: ReadableStream; httpEtag: string } | null>;
}

interface Env {
  /** Optional until R2 is enabled on the account — see wrangler.jsonc. */
  WEBZJS?: WebzjsBucket;
  SESSION_SECRET?: string;
  [key: string]: unknown;
}

interface WorkerHandler {
  fetch(request: Request, env: Env, ctx: ExecutionCtx): Promise<Response>;
}

interface ExecutionCtx {
  waitUntil(promise: Promise<unknown>): void;
}

// Workers' cache API; lib.dom's CacheStorage has no `default`.
const edgeCache = (caches as unknown as { default: Cache }).default;

const MIME: Record<string, string> = {
  wasm: 'application/wasm',
  js: 'text/javascript',
  mjs: 'text/javascript',
  json: 'application/json',
};

// Mirror of next.config.mjs headers(): SharedArrayBuffer (the wasm thread
// pool) needs a cross-origin-isolated page, which needs COOP+COEP.
const PAGE_HEADERS: Record<string, string> = {
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Embedder-Policy': 'require-corp',
};

async function serveWebzjs(
  request: Request,
  env: Env,
  ctx: ExecutionCtx,
  url: URL,
): Promise<Response> {
  if (!env.WEBZJS) {
    return new Response(
      'webzjs artifacts unavailable: R2 bucket binding not configured',
      { status: 404 },
    );
  }

  // Every R2 read is a billed operation and these artifacts change only on
  // a vendor re-upload, so serve repeats from the edge cache. Browser cache
  // alone doesn't help first visits, and 57 MB of wasm per new learner adds
  // up against the free tier. The cache key is always a GET: the Cache API
  // refuses HEAD puts, and a HEAD should see identical headers anyway.
  const cacheKey = new Request(url.toString());
  const cached = await edgeCache.match(cacheKey);
  if (cached) {
    return request.method === 'HEAD' ? new Response(null, cached) : cached;
  }

  const key = url.pathname.slice('/webzjs/'.length);
  const object = await env.WEBZJS.get(key);
  if (!object) return new Response('not found', { status: 404 });

  const ext = key.split('.').pop() ?? '';
  const response = new Response(object.body, {
    headers: {
      // Explicit type: the wasm loader (and streaming compilation) rejects
      // anything but application/wasm.
      'Content-Type': MIME[ext] ?? 'application/octet-stream',
      // The URL is not content-addressed, so long-lived but not immutable.
      'Cache-Control': 'public, max-age=3600',
      // Satisfies the COEP require-corp documents; same-origin today, but
      // explicit CORP keeps a future CDN/custom-domain URL working too.
      'Cross-Origin-Resource-Policy': 'cross-origin',
      ETag: object.httpEtag,
    },
  });

  ctx.waitUntil(edgeCache.put(cacheKey, response.clone()));
  // A HEAD still warms the cache above; it just answers without the body.
  return request.method === 'HEAD' ? new Response(null, response) : response;
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionCtx): Promise<Response> {
    // Without the secret, sessions would be signed with whatever fallback
    // leaked into the bundle. Refuse to serve instead.
    if (!env.SESSION_SECRET) {
      throw new Error(
        'SESSION_SECRET is not set — run `npx wrangler secret put SESSION_SECRET`',
      );
    }

    const url = new URL(request.url);
    const readMethod = request.method === 'GET' || request.method === 'HEAD';
    if (url.pathname.startsWith('/webzjs/') && readMethod) {
      return serveWebzjs(request, env, ctx, url);
    }

    const response = await (handler as WorkerHandler).fetch(request, env, ctx);

    const missing = Object.entries(PAGE_HEADERS).filter(
      ([name]) => !response.headers.has(name),
    );
    if (missing.length === 0) return response;

    const patched = new Response(response.body, response);
    for (const [name, value] of missing) patched.headers.set(name, value);
    return patched;
  },
};
